- schema/deploy/shipping/views@2019-04-19.sql
- schema/revert/shipping/views.sql
- schema/revert/shipping/views@2019-04-19.sql
- schema/sqitch.plan
- schema/verify/shipping/views@2019-04-19.sql
Time binning is useful for the modeling and viz efforts, so it's nice to
harmonize that early in the data flow rather than separately several
times.  Weeks are the standard time bin used in epidemiology.
Note that the WHO's epi weeks, synonymous with ISO weeks, are slightly
different from CDC's epi weeks, as described most succinctly¹
> The US CDC defines epidemiological week (known as MMWR week) as seven
> days beginning with Sunday and ending with Saturday. The WHO defines
> epidemiological week, based on ISO week, as seven days beginning with
> Monday and ending with Sunday. In either case, the end of the first
> epidemiological week of the year by definition must fall at least four
> days into the year. Most years have 52 epidemiological weeks, but some
> have 53.
It's my …
> Add ISO week of encounter to incidence model observation view

- schema/deploy/roles/incidence-modeler/grant-select-on-age-bins.sql
- schema/revert/roles/incidence-modeler/grant-select-on-age-bins.sql
- schema/sqitch.plan
- schema/verify/roles/incidence-modeler/grant-select-on-age-bins.sql
This lets them pull the full set of ranges possible for modeling
purposes, even if the data doesn't cover all bins.
> Grant incidence-modeler select on shipping.age_bin_{fine,coarse}

- lib/seattleflu/db/cli/command/etl/enrollments.py
Audere made some small, backwards-compatible tweaks to the document
schema.  Our version check caught the version bump and bailed for human
intervention.  I verified the changes are ok.  In testing, I discovered
that some of the "chosenOptions" arrays have string elements.  This
violates the type defined in Audere's hutchProtocol.ts which requires
integer elements, so I guess the documents aren't actually type-checked
before being sent to us.  Handle it by forcing integers, which will fail
on unconvertible values.
> etl enrollments: Handle flu@home documents

- bin/id3c
- lib/seattleflu/db/cli/__init__.py
- lib/seattleflu/db/cli/__main__.py
- lib/seattleflu/db/cli/command/etl/__init__.py
- lib/seattleflu/db/cli/command/identifier.py
This makes for nicer command-line invocations, and also means it may be invoked from outside of the project repo.
> Allow bin/id3c to be invoked without pipenv

- lib/seattleflu/db/cli/command/etl/presence_absence.py
Matthew from NWGC pushed a different kind of document that nests items
inside a top-level "Update" key instead of within "store" → "items".
This document structure will be used by Samplify to send us updates to
previously sent items.  Our ETL process doesn't need that distinction,
so we look for one and then the other.
This will unstick the presence/absence ETL once deployed.
> etl presence-absence: Handle another kind of container in the document

- lib/seattleflu/db/cli/command/etl/presence_absence.py
Update the presence-absence etl process to
grab the NWGC sample ID that comes with the
test results and add it to the sample details within
warehouse schema.
This will make pairing between NWGC sample ID
and SFS UUID much easier in the future for 
assembly work.
> Add NWGC sample ID to sample details

- lib/seattleflu/db/cli/command/etl/clinical.py
- lib/seattleflu/db/cli/command/etl/enrollments.py
- schema/deploy/functions/age_conversion.sql
- schema/deploy/shipping/age-bin-v2.sql
- schema/deploy/shipping/views.sql
- schema/deploy/shipping/views@2019-06-03-age-column.sql
- schema/deploy/types/intervalrange.sql
- schema/deploy/warehouse/encounter/age.sql
- schema/revert/functions/age_conversion.sql
- schema/revert/shipping/age-bin-v2.sql
- schema/revert/shipping/views.sql
- schema/revert/shipping/views@2019-06-03-age-column.sql
- schema/revert/types/intervalrange.sql
- schema/revert/warehouse/encounter/age.sql
- schema/sqitch.plan
- schema/verify/functions/age_conversion.sql
- schema/verify/shipping/age-bin-v2.sql
- schema/verify/shipping/views.sql
- schema/verify/shipping/views@2019-06-03-age-column.sql
- schema/verify/types/intervalrange.sql
- schema/verify/warehouse/encounter/age.sql
This PR pulls age out of the encounter details into a column for the encounter table. 
After much discussion with @tsibley, we decided that the best data type for the age column is [intervals](https://www.postgresql.org/docs/11/datatype-datetime.html#DATATYPE-INTERVAL-INPUT), since it is much more human-readable than large numbers in months or age in floats. 
Public functions are created to convert the intervals to numeric values in both months and years. These are used in the modeling views since the modeling teams have a preference for numeric types.
> Encounter age

- lib/seattleflu/db/cli/command/manifest.py
These changes pull in the following (optional) additional columns from the manifest data, inserting them into sample details
* aliquot date
* rack identifiers
* test results
* notes
> Pull extra manifest data

- lib/seattleflu/db/__init__.py
- lib/seattleflu/db/cli/command/__init__.py
- lib/seattleflu/db/cli/command/user.py
This is to support the dev team (myself included) making new users more
easily, in particular with regard to standardized password generation.
Next steps to round this out might include implementing:
* `id3c user role ls`
* `id3c user grant <username> <role> [<role>, …]`
* `id3c user revoke <username> <role> [<role>, …]`
* `id3c user expire <username>`
* `id3c user delete/rm <username>`
> Support basic user creation and listing from the CLI

- README.md
- lib/seattleflu/api/routes.py
- lib/seattleflu/api/static/index.html
From Trello:
> This provides better versioning and namespacing for growth and also means we can share nouns for resource endpoints between the receiving area and warehouse area, e.g.:
> 
> ```
> /v1/receiving/presence-absence
> /v1/warehouse/presence-absence
> ```
> 
> Support old endpoints as deprecated aliases for now, then work on getting consumers of the API moved over.
> Move existing api underneath /v1/receiving

- lib/seattleflu/db/cli/command/clinical.py
- lib/seattleflu/db/cli/command/manifest.py
- lib/seattleflu/db/session.py
Improves transaction time by a couple orders of magnitude, from hours to
1-2 seconds.
The little bit of escaping awkwardness is encapsulated into a
DatabaseSession method to keep it nicely contained.
> clinical/manifest upload: Copy NDJSON stream instead of inserting individually

- lib/seattleflu/db/cli/command/clinical.py
See notes in commit messages. The encounter identifiers changed between the last load and this one because we accidentally tweaked how we were handling dates.
> Fix encounter identifier generation for SCH clinical data

- lib/seattleflu/db/cli/command/clinical.py
This was accounted for in our separate manifest parsing, but not in the
different parsing of the manifest here.  The effect was that ~2,600 records
were skipped due to missing barcodes when reloading the clinical data
earlier today.
In the (hopefully near) future, we won't need to do the merge here and
this code will be deleted.
> clinical parse-uw: Account for column name change in HMC manifest

- lib/seattleflu/db/cli/command/clinical.py
Previously pandas was converting `census_tract` on read to `float`. 
Now we're declaring `census_tract` as a `string` on pandas read_(csv/excel).
This PR also includes some minor refactoring for consistency between UW and SCH preprocess and 
punting null values mapping from clinical back to preprocess (by using `na_values` on pandas read).
> Census tract as string

- schema/deploy/roles/kit-processor/create.sql
- schema/deploy/roles/kit-processor/grants.sql
- schema/revert/roles/kit-processor/create.sql
- schema/revert/roles/kit-processor/grants.sql
- schema/sqitch.plan
- schema/verify/roles/kit-processor/create.sql
- schema/verify/roles/kit-processor/grants.sql
Creates kit process role in the database via sqitch
to allow the automation of kit etl jobs. 
There was no need to create a `kit uploader` role
because the kit etl pulls data from `receiving.manifest` 
and `receiving.enrollment` which already have their
own uploaders.
> Create kit processor role for automation

- lib/seattleflu/db/cli/command/etl/__init__.py
- lib/seattleflu/db/cli/command/etl/clinical.py
- lib/seattleflu/db/cli/command/etl/longitudinal.py
- lib/seattleflu/db/cli/command/etl/presence_absence.py
Move the `SampleNotFoundError` from the `presence_absence` ETL routine
to a shared module. The `clinical` and `longitudinal` ETL routines were
previously importing it from `presence_absence`; this new, shared
location is more sensible.
> etl: move `SampleNotFoundError` to shared module

- schema/sqitch.plan
We've been using tags a bit backwards.  Typically tags are markers of
when changes are merged/released/deployed, but we've only been creating
them when we need to rework changes.  Sometimes the tag names
incorporate the foreseen rework even though they identify the change
_before_ that rework takes place.  :-)
I would like to move to a tagging workflow where all branches that make
schema changes include a new sqitch tag.  Tags will then mark groups of
schema changes when they happen instead of after the fact, and it should
make reworks slightly nicer since a tag will already exist.
Tags used in this manner are effectively schema versions, which is a
very typical use case.  I think using [calendar versions](https://calver.org) makes sense
here for two main reasons:
* It's easier to mint …
> Start of a new way to handle schema tags

- README.md
- lib/seattleflu/db/cli/command/__init__.py
- lib/seattleflu/db/cli/command/reportable_conditions.py
- lib/seattleflu/db/session.py
This is the VIEW version of https://trello.com/c/coA6Z3dR/11-reportable-condition-notifications. It includes seattleflu/id3c-customizations/pull/2. 
In this PR:
`warehouse.presence_absence` has a new `processing_log` column that is updated after a Slack 
notification.
`shipping.reportable_condition_v1` is a true view that reflects the Slack message status of reportable
conditions from `warehouse.presence_absence`.
> Reportable notifications view

- lib/seattleflu/labelmaker.py
Just printed a batch of these.  We need to make this more general, but
no time right now.
> labelmaker: Support year 2 identifier sets/barcode types

- lib/seattleflu/db/cli/command/etl/consensus_genome.py
This addresses issue #59 
Update the consensus genome etl to create more unique identifiers
for genomic sequences by adding the sequence read set id to the end
of the identifiers.
I have not updated the REVISION number because we don't want the
etl process to double insert the same sequences (there will not be an
identifier conflict with previously created sequences).
The genomic sequences that are already within production will need to
be updated manually. (The genomic sequences will need to be wiped 
anyways to include changes made with https://github.com/seattleflu/assembly/pull/13)
> Update consensus genome etl

- lib/seattleflu/__init__.py
- lib/seattleflu/db/cli/command/etl/kit.py
Previously uncaught exceptions that were process-terminating were emitted to stderr, but not through the rest of the logging handlers (like /var/log/syslog).
> Exception logging

- lib/seattleflu/db/cli/command/etl/longitudinal.py
- lib/seattleflu/db/cli/command/longitudinal.py
I _believe_ this fix is now incorporating symptoms into the `etl longitudinal` pipeline. 
However, I am unable to restore my local database from a copy of production since @tsibley's `location` changes. 
I'm hoping to debug this with him in person on Monday so I can fully test this PR.
> longitudinal: update ETL to extract symptoms

- lib/seattleflu/db/cli/command/__init__.py
- lib/seattleflu/db/cli/command/redcap_det.py
Get REDCap records that have been created/modified since a provided
start date. Parse the records into "fake" DET records and print
as NDJSON. Upload created DET records to receiving.redcap_det
This creates "fake" DET records that mimics REDCap DETs but is missing `project_url` and `username`. I don't really see a way to parse these from the record data returned from REDCap, so if we do want to include them, I think they just need to be additional options in the `redcap-det parse` command. I don't think they are crucial to the ETL process so omitted for now.
> Add `redcap-det` commands

- Pipfile
- Pipfile.lock
- schema/deploy/warehouse/identifier/triggers/barcode-distance-check.sql
- schema/deploy/warehouse/sequence-read-set/triggers/urls-unique-to-one-set.sql
- tests/search-path.py
While reviewing #75, I recalled wanting a test like this at the time we switched from `set` to `set local` (a985ed1). Now that we had an easier testing setup, I thought I'd be able to get this going in an hour, so I did.
> Tests: Check that our SQL changes don't use unlocalized set search_path commands

- lib/id3c/cli/command/manifest.py
Update `manifest parse` to include columns `sample_origin` and `swab_site`.
Manifests for 2019-2020 are all contained within one workbook and one sheet. To infer `site` from manifest data for reportable conditions, we need to include `sample_origin` and `swab_site`.
> Add sample origin and swab site

- lib/id3c/api/datastore.py
- lib/id3c/api/routes.py
- lib/id3c/api/static/index.html
This route expects Content-Type of `application/fhir+json`
> api: Add endpoint to receive FHIR documents

- lib/id3c/api/routes.py
Loads all extra API endpoints from extensions through entry point "id3c.api.routes"
This must be at the end of route declarations to allow customization of existing routes and to avoid dependency errors.
Required for PR https://github.com/seattleflu/id3c-customizations/pull/16
> Load extra API routes from extensions

- lib/id3c/cli/command/__init__.py
- lib/id3c/cli/command/etl/presence_absence.py
- lib/id3c/cli/command/receiving.py
- lib/id3c/cli/command/sequence_read_set.py
Samplify will be sending documents with a top level "samples" key and
a "chip" key for each sample. 
~For each presence/absence result, the unique identifier will become "NWGC/`sampleId`/`chip`/`target_id`". `sampleId` and `chip` will both come from Samplify.
`target_id` for the target found or created within ID3C `warehouse.target`.~
`presence_absence.identifier` will become `NWGC/chip/sampleId/geneTarget` with all parts of the identifier coming from the Samplify document.
This change does bring up the question of how should we handle the old presence/absence results already within `warehouse.presence_absence`. Matthew did [offer](https://seattle-flu-study.slack.com/archives/CJU8RN2Q6/p1571943038028500?thread_ts=1571942534.026100&cid=CJU8RN2Q6) to send previous runs with chip …
> Update etl presence-absence

- lib/id3c/cli/command/etl/presence_absence.py
Our custom reporting process stashes its log entries in presence/absence
details, but the log was being blown away when updates came in.  This
caused mass re-reporting today as we processed a large repush of
existing data.  More thorough testing (mea culpa) all the way through
the reporting process would have caught this.
This coalesce + append is the general pattern we should use so that
multiple things can cooperatively use the details column without knowing
about each other.
---
I haven't tested this yet, but we should!
> etl presence-absence: Preserve existing details when updating an existing row

- Pipfile.lock
- lib/id3c/cli/command/__init__.py
- lib/id3c/cli/command/de_identify.py
- lib/id3c/cli/command/geocode.py
- lib/id3c/cli/command/location.py
- lib/id3c/db/types.py
- mypy.ini
- setup.py
Adds `geocode`, `location lookup` and `de-identify` to ID3C. 
See commit messages for specifics of each command. 
A couple things I would like to discuss:
1. the names of the `geocode` subcommands (naming is hard 😭)
2. whether we should limit `location lookup` to return only one location
3.  where should PII be standardized? currently `de-identify` expects values to already be canonicalized.
> Geocode, location lookup, and de-identify

- lib/id3c/cli/command/location.py
While I got the right CRS in the schema, the location command was
enforcing the wrong one.  I clearly mixed up the numbers.
To correct existing data, a manual update can be run which does:
st_transform(st_setsrid(polygon, 4269), 4326)
for the point, polygon, and simplified_polygon columns.
For future data which isn't already in 4326 (like official Census tract
geometries), we'll need to add support for re-projection during location
import.  Alternatively, we can re-project before import as a
pre-processing step, but I think it'd be nicer to add built-in support.
> location: Require EPSG:4326 (WGS84) not EPSG:4269 (NAD83)

- lib/id3c/cli/command/redcap_det.py
- lib/id3c/cli/redcap.py
Add the ~`end_date`~ `until_date` option to generate DETs for records created/modified before the given timestamp.
If both `since_date` and ~`end_date`~ `until_date` are provided then only generates DETs for records created/modified in that timeframe.
> Redcap DET end date

- lib/id3c/cli/command/etl/fhir.py
Bumps FHIR etl to REVISION 2 to include updates in response to warning logs in recent etl runs.
* `strip()` barcode values
* skip location references within Encounter resource if the location is a site because it will get processed separately than the other locations. This will reduce the number of "No reference set, cannot resolve" warnings. 
* If a location that is _not_ a site and has no reference, then we also include our own warning. Not entirely sure how to make this warning more meaningful/actionable.
> FHIR etl updates

- lib/id3c/cli/command/geocode.py
Lower the log level of the invalid address warning when a lookup returns
no response from SmartyStreets. As a result, we will receive fewer,
cluttering warnings in our #id3c-alerts channel.
> geocode: Lower log level of invalid address

- schema/deploy/fuzzystrmatch.sql
- schema/revert/fuzzystrmatch.sql
- schema/sqitch.plan
- schema/verify/fuzzystrmatch.sql
Actually performing correction is left as an exercise for the user
(ourselves, later!).
Unlike our existing `hamming_distance()` function used in minting
identifiers/barcodes, the Levenshtein distance functions work with
strings of different lengths (which is important for correction tasks).
> Install fuzzystrmatch extension to allow easier identifier/barcode correction

- lib/id3c/cli/command/redcap_det.py
- lib/id3c/cli/redcap.py
This is handy when testing and also may be useful if a specific set of records needs to be re-ingested due to a bad import.
> redcap-det generate for specific records

- lib/id3c/cli/command/etl/redcap_det.py
- lib/id3c/cli/command/redcap_det.py
- lib/id3c/cli/redcap.py
The REDCap project created by ITHS for our UW retrospective data pulls is setup a bit differently than the prospective projects created by Helen's team.
With these new options and fixes in place, the plan is to setup a cronjob which regularly generates and uploads DETs for the project to trigger a new REDCap ETL.
> redcap-det generate support for more diverse REDCap projects

- lib/id3c/cli/command/geocode.py
If no address is found from first attempt at geocoding, try to extract address from text using SmartyStreet US Extract API.
Realized we need this feature for the clinical data pull REDCap project, since addresses are in a single text field.
> geocode: extract address from text

- lib/id3c/cli/command/etl/redcap_det.py
This allows the etl to pull redcap-records even if the instrument in the DET is marked incomplete.
This is necessary for pulling REDCap records from the Clinical Data Pulls project since the instruments will not be marked "complete" by ITHS.
> etl redcap-det: add --include-incomplete flag

- Pipfile
- Pipfile.lock
- lib/id3c/cli/command/manifest.py
- lib/id3c/cli/io.py
- lib/id3c/logging/data/default.yaml
- mypy.ini
- setup.py
This is particularly handy with sensitive manifest data kept on S3 and avoids boilerplate file download/delete juggling around the parse step.
A useful future improvement might be to wrap up fsspec into something like id3c.cli.types.File, which would provide a click.File-like argument "type", complete with proper closing behaviour.  It seemed premature to do so now, but may become more timely if we start adding URL-support to other commands.
> manifest parse: Support reading from remote manifest files

- lib/id3c/__version__.py
- lib/id3c/cli/command/__init__.py
- lib/id3c/cli/command/manifest.py
- setup.py
Pandas finally has a non-zero major version number and a semver policy! \o/
Allows byte strings to be passed directly to pandas.read_excel() instead
of requiring that they're wrapped in ByteIO objects.  This is relevant
for the new remote URL support added to the manifest command, which I
tested under Pandas 1.x.  It doesn't work when using the older Pandas
pinned in our production environment, which I had pinned to avoid
backwards compat issues.
This version of Pandas also includes a nice true string dtype instead of
using the very generic object dtype.  The string dtype is more
restrictive than object and will only accept actual strings.  This is
what we wished we had when previously writing dtype=str.
A new deprecation warning about the future removal of pandas.np is
avoided by …
> Upgrade pandas to newly released version 1.0.1

- lib/id3c/cli/command/location.py
This makes hierarchy dynamic per feature without modifying the GeoJSON.
`--hierarchy-by-feature` option takes a CSV file that must have the column "feature_identifier". All other column headers are assumed to be hierarchy keys.
This option overrides `--hierarchy-from` and can override `--hierarchy` if the they have the same keys.
My questions are:
1. should we have a hard coded list of supported hierarchy keys instead of just ingesting all columns within the CSV file?
1. how should we deal with duplicates of a feature_identifier? (it currently just takes the first record)
> location: add `hierarchy-by-feature` option

- lib/id3c/cli/command/etl/__init__.py
- lib/id3c/cli/command/etl/consensus_genome.py
This is a non-error condition for the callers, which check the return
value of find_sample() and take the appropriate action.  In some cases,
the caller will raise its own error.  In other cases, like the FHIR ETL,
the sample will be created and logging an error a) does not make sense
and b) makes the automated jobs noisy.  The decision is best left to the
caller.
The error level may have made more sense at a time when find_sample()
raised its own error instead of returning None.
> Reduce log level from error → info when a sample cannot be found

- lib/id3c/cli/command/etl/fhir.py
Our internally created Diagnostic Reports have a literal reference to
a Specimen within the same bundle rather than a logical reference.
This updates the `process_diagnostic_report_bundle_entry` to handle both
> etl fhir: handle literal references to Specimen

- lib/id3c/cli/command/etl/fhir.py
1. Instead of assuming the first identifier is our internal identifier, find the correct identifier that matches our interal system.
2. Skip results that have snomed code '911000124104' which marks the result Inconclusive
> Update FHIR ETL for Cepheid results

- lib/id3c/cli/io/pandas.py
Without a default `sheet_name`, our `read_excel` function defaults to
`None`. Unfortuantely, this causes `pd.read_excel` to return a
`Dict[str, pd.DataFrame]` instead of a DataFrame as we would expect.
We're not specifying a sheet name as an argument in the
`load_file_as_dataframe` function, so hard-code the first sheet (0)
as the `sheet_name` argument.
> Add default sheet_name to load_file_as_dataframe

- lib/id3c/cli/command/etl/fhir.py
- lib/id3c/cli/command/etl/presence_absence.py
- schema/deploy/shipping/views@2020-02-11.sql
- schema/revert/shipping/views.sql
- schema/revert/shipping/views@2020-02-11.sql
- schema/sqitch.plan
- schema/verify/shipping/views@2020-02-11.sql
Add `device` to `presence_absence.details` to help differentiate presence/absence results. 
In `etl presence-absence` the device is hardcoded to `OpenArray` since that it only ingests NWGC results.
`etl fhir` uses the Observation Device Identifier value. 
Also created a new view `shipping.presence_absence_results_v2` to include a device column.
> Add presence absence device

- docs/CODEOWNERS
A few less clicks on every PR!  Also enables some nice UI affordances on
GitHub.  Docs about CODEOWNERS at:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
> Add a GitHub CODEOWNERS file so reviewers are automatically requested

- lib/id3c/api/routes.py
They can often be quite large and cause syslog errors, which has maximum
message sizes.  We also don't necessarily want to push all our received
data into the logs.
> api: Stop logging the entirety of received JSON documents

- lib/id3c/cli/command/etl/redcap_det.py
- lib/id3c/cli/redcap.py
The default value for `raw_coded_values` is False, so we don't need to update the existing custom redcap-det ETLs. 
This will allow us to pull the coded values for the SCAN redcap project.
> etl redcap-det: allow raw coded values for multiple choice

- lib/id3c/cli/command/etl/__init__.py
Always include a new location's own `scale => identifier` in
its hierarchy.
On update, new hierarchy and exisiting hierarchy are concatenated, with
new hierarchy taking precedence if keys overlap.
> etl `upsert_location`: include new location's own hierarchy

- schema/deploy/warehouse/encounter-location-relation.sql
- schema/deploy/warehouse/encounter-location-relation/data.sql
- schema/deploy/warehouse/encounter-location/relation-fk.sql
- schema/deploy/warehouse/primary-encounter-location.sql
- schema/revert/warehouse/encounter-location-relation.sql
- schema/revert/warehouse/encounter-location-relation/data.sql
- schema/revert/warehouse/encounter-location/relation-fk.sql
- schema/revert/warehouse/primary-encounter-location.sql
- schema/sqitch.plan
- schema/verify/warehouse/encounter-location-relation.sql
- schema/verify/warehouse/encounter-location-relation/data.sql
- schema/verify/warehouse/encounter-location/relation-fk.sql
- schema/verify/warehouse/primary-encounter-location.sql
Creates a framework for prioritizing encounter-locations by relation and
uses that in a new view that subsets warehouse.encounter_location to
just the "primary" rows.  A default set of relations and priorities is
added, but these can be tailored for each database since they are just
rows in a controlled vocabulary table.
This provides support to queries which want to only follow a single link
across the one-to-many relationship without hardcoding a specific
relation (e.g. to choose the "best" location available when the data is
sparse).
> Add the concept of a "primary" encounter location

- lib/id3c/cli/command/etl/fhir.py
Now that we're ingesting clinical test results (sample barcodes instead of only collection barcodes), update the FHIR ETL logic for barcode lookup.
> Diagnostic report identifier sets

- lib/id3c/cli/command/etl/fhir.py
Expects to find at most one preferred language per patient, and will error if it finds more than one preferred language.
Adds the language code to `encounter.details` as we have done in Y1 data.
> etl fhir: process patient preferred language

- lib/id3c/cli/command/etl/fhir.py
Now allows Bundles without Specimen Resources. If a Patient Resource
is present, make sure that there is at least one Encounter Resource.
Only check the number of Observation Resources if a Specimen Resource
is present because we are using these Observation Resources to link
Patient, Encounter, and Specimen.
> etl fhir: update `assert_required_resource_types_present`

- lib/id3c/cli/command/etl/manifest.py
Add `collections-scan` to the list of hard-coded, acceptable collection
identifier sets for the manifest ETL.
> etl manifest: Add SCAN collection identifier set

- lib/id3c/labelmaker.py
Add a new sample (aliquot) barcode collection for HAARVI as requested by
Caitlin. She wanted singlet barcodes in the triplicate format (i.e.
small barcodes) for the HAARVI sub-study.
---------------------------------------
As far as I know, new identifier sets are added manually (outside of sqitch) to ID3C. So, I would have to run the following SQL before deploying this branch:
```sql
insert into warehouse.identifier_set (name, description) values ('samples-haarvi', 'Aliquoting sample barcodes for collections-haarvi');
```
> labelmaker: Add new samples-haarvi layout

- lib/id3c/cli/command/etl/fhir.py
In the SCAN REDCap-DET ETL, we recently started adding a specimen note
if a sample is unable to be tested ("never-tested").
Ingest this attribute, placing it in sample.details under the key,
"note".
> etl fhir: Ingest Specimen.note

- lib/id3c/labelmaker.py
Sample barcodes are only needed in duplicate since the lab is no longer
doing the C aliquot.
This updates the labels to print duplicate barcodes, with 3 pairs
per row and the last column blank.
> labelmaker: update SamplesLayout to print duplicates

- lib/id3c/cli/redcap.py
See commits. I added these when I was prototyping a REDCap project "switchboard" which constructs direct links to REDCap records. These changes aren't directly necessary by anything yet, but seemed generally useful to add to this growing REDCap library (which maybe should be spun out into a separate package sooner than later?).
> REDCap fields and version

- lib/id3c/cli/command/etl/manifest.py
- schema/deploy/warehouse/sample/collection-date.sql
- schema/revert/warehouse/sample/collection-date.sql
- schema/sqitch.plan
- schema/verify/warehouse/sample/collection-date.sql
Add `collection_date` to `warehouse.sample` and ingest this field from the manifest ETL.
I've added a `validate_date` function to clean up the manually entered collection date column from the aliquoting manifest. 
1. Do we want to use this to check that the date is not too old or a future date as well? (We currently have a sample from 1911-04-04 😆 )
2. Do we want `sample.details.date` to hold the raw value from the aliquoting sheet or should we update that to be the cleaned up date value as well?
> Sample collection date

- lib/id3c/cli/command/etl/fhir.py
Some updates to the FHIR ETL to allow ingestion of the SCAN follow-up encounter:
* Allow FHIR bundle to have multiple Encounter resources even if it only has one Specimen resource
* Ingest `Encounter.reasonCode` into `encounter.details.reason` to allow for differentiation of follow-up encounters from primary encounters.
> Scan follow up fhir

- lib/id3c/cli/command/__init__.py
- lib/id3c/cli/command/refresh_materialized_view.py
- schema/deploy/roles/materialized-view-refresher/create.sql
- schema/deploy/roles/materialized-view-refresher/grants.sql
- schema/revert/roles/materialized-view-refresher/create.sql
- schema/revert/roles/materialized-view-refresher/grants.sql
- schema/sqitch.plan
- schema/verify/roles/materialized-view-refresher/create.sql
- schema/verify/roles/materialized-view-refresher/grants.sql
Add role and command to refresh materialized views.
Moved from id3c-customizations with @tsibley's suggestion:
>Hmm, and actually, what about building this into a core ID3C CLI command? It's something I expect will be not uncommon. (I'm actually really surprised it took us this long to need materialized views! I'd thought we'd hit a need for them much sooner.) I guess this would mean moving the materialized-view-refresher role to core, though, which is maybe more shuffling than we want to bother with right now…
> Materialized view refresher

- lib/id3c/cli/command/etl/redcap_det.py
1. Aggregate DETs by record. Skip old DETs and only process the latest
complete DET for each record.
2. Make a batch request for records instead of requesting each record
individually from the REDCap API.
Note that this ETL still has the caveat of not being able to handle
records with repeating instruments or longitudinal events.
> optimize REDCap DET ETL

- lib/id3c/cli/command/etl/fhir.py
Ingests into `warehouse.presence_absence.details.effective_datetime`
This change was made due to a request from the self-test team to report the time at which the participants performed the self-test for Ellume.
> etl fhir: ingest `effectiveDateTime` from Diagnostic Reports

- lib/id3c/labelmaker.py
Labeled as `SCAN - STAVE` for surge testing around vulnerable/exposures.
Currently only needs barcode in singlet.
Barcode arrangements originally discussed on [slack](https://seattle-flu-study.slack.com/archives/CDCJPAW2E/p1594763447062000)
I ran the following to create the identifier set in the database:
```
pipenv run id3c identifier set create "collections-scan-kiosks" "Seattle Coronavirus Assessment Network kiosks for surge testing around vulnerable/exposures"
```
> labelmaker: Add layout for collections-scan-kiosks

- lib/id3c/cli/command/etl/fhir.py
Making this PR as a reminder that this change needs to be deployed along with https://github.com/seattleflu/id3c-customizations/pull/118.
Although there's also nothing stopping from this being deployed before 😄
> etl fhir: add new SCAN identifier set

- lib/id3c/cli/redcap.py
Extend encapsulation by supporting three-valued logic. Makes it easier
for us to differentiate between an incomplete instrument and the
instrument not existing in data.
> redcap is_complete: return None if {instrument}_complete does not exist

- lib/id3c/cli/command/redcap_det.py
- lib/id3c/cli/redcap.py
Add an `--event` option to the REDCap DET generate command.
Add an `events` attribute to the REDCap `Project` class.
Do some minor reworking/refactoring of the generate command.
> Redcap det event

- schema/deploy/shipping/age-bin-decade.sql
- schema/revert/shipping/age-bin-decade.sql
- schema/sqitch.plan
- schema/verify/shipping/age-bin-decade.sql
Decade age bins to be used in the views for Formative APIs. 
It seems like a common enough need to be included in ID3C core.
> Add decade age bins

- lib/id3c/cli/command/etl/fhir.py
- lib/id3c/cli/command/etl/manifest.py
- lib/id3c/utils.py
See commit messages for details on the functionality.
In particular, I'd like feedback on the update-if-not-null behaviour that both the manifest and FHIR ETLs now do for `warehouse.sample.collected`. I think it makes sense, but it does introduce an uncertainty about where the date comes, as for any given record it now depends on what ETL received data and processed it most recently. They _should_ both agree, but of course in practice there will probably be times when they don't.
> Ingest sample.collected date from FHIR Specimen collection

- lib/id3c/labelmaker.py
This is a PR for a barcode layout to go with a new identifier set.
The identifier set has already been created. It's called collections-household-general-season-three (I put season three in the name to help [me] distinguish it from the 4 other household collection set identifiers.)
The request in Slack from Roni was:
"is it possible to get 115 sheets of orange Household barcodes? This is for the upcoming, general Household year 3 study."
"these are for this upcoming year's household study, which is no longer 'household observation' but just the household study. We only need single barcodes for this (printed just once) thanks!"
> Add barcode layout for season 3 househould arm

- lib/id3c/cli/redcap.py
Helpful for reducing the number of fetched records when the record ids
aren't known.
> redcap: Support for a conditional logic filter when fetching records

- lib/id3c/labelmaker.py
Add two new layouts for the UW Reopening (a.k.a. Husky Coronavirus
Testing) study collection barcode sets.
> labelmaker: Add layout for UW Reopening barcodes

- Pipfile
- Pipfile.lock
- lib/id3c/cli/command/etl/manifest.py
- lib/id3c/cli/command/manifest.py
- lib/id3c/cli/io/google.py
- mypy.ini
- setup.py
In this PR, the manifest and etl/manifest modules are updated to accommodate other types of manifests that may have a collection barcode but not a sample barcode and may not have a collected date. A google module is also added to io, and in this module is utility code for downloading a document from Google Drive.
Restrictions are loosened so that a sample barcode is not required. Checks are in place, though, to ensure that a sample barcode or a collection barcode (or both) are provided. We need at least one of the two barcodes. 
For manifest YAML configuration (and the options for the parse method) three settings are now special:
1. sample (This was already there. The change is that is no longer required). In the receiving.manifest table, data mapped to 'sample' end up the in the JSON …
> Ingest incident report manifest

- lib/id3c/db/session.py
- lib/id3c/utils.py
This helps identify connections originating from within ID3C code when
looking at Postgres' pg_stat_activity.
By specifying a default, specific jobs or invocations can still provide
a more usage-specific name via the PGAPPNAME environment variable (e.g.
alongside the credential variables) if desired.
> db session: Provide a default application name

- lib/id3c/cli/command/etl/redcap_det.py
- setup.py
Alleviates presumed strain on the REDCap API in cases when we bump an ETL revision and refetch ~everything from a very large project (as just happened with the Husky Coronavirus Testing project, but could also happen with SCAN).
Batch size to fetch defaults to 5,000, but can be tuned at invocation using the new --fetch-batch-size option.  5,000 is a mostly arbitrary number.  It might not be the best value for any project and is certainly not the best value for all projects or servers.
All records are still fetched up-front and held in memory before the underlying ETL routine is called in a loop.  A future improvement would be to process each batch before fetching the next, but that requires partitioning the set of DETs too.
> etl redcap-det: Fetch records from REDCap in batches no larger than 5,000

- lib/id3c/cli/command/manifest.py
- lib/id3c/cli/io/google.py
See the commit messages for details.
This PR adds a function to get Google Drive document metadata and then uses that to create the digest for the incident report manifest.
> Google doc metadata

- lib/id3c/cli/command/etl/fhir.py
~Splits the expected REDCap URL into individual keys within
`encounter.details`.~
See latest commit for details
Should be deployed along with https://github.com/seattleflu/id3c-customizations/pull/148
> etl fhir: Add REDCap source details to `encounter.details`

- lib/id3c/cli/redcap.py
This short change adds event name and repeat instance ID to the REDCap Record object.
I haven't seen anything that indicates that the field names for these vary across projects, so I did not make the field names project attributes like we do for record_id.
> Add event name and instance ID to REDCap Record

- lib/id3c/cli/command/etl/fhir.py
- lib/id3c/cli/command/etl/manifest.py
Add `collections-childcare` identifier set to the manifest and FHIR ETLs.
> Childcare identifier

- lib/id3c/cli/command/etl/redcap_det.py
This will help us manage large numbers of DETs from Husky Coronavirus
Testing (and SCAN) when bumping ETL revisions and reprocessing
everything.  With a limit, subsequent ETL jobs are responsible for
picking up remaining DETs to process.
> etl redcap-det: Add optional --limit on number of received DETs

- lib/id3c/cli/io/google.py
Don't assume that every field in the metadata of a Google doc will
always exist. In production we just had an occurrence of the
`lastModifyingUserName` not coming back in the details.
> Accommodate missing metadata fields for Google doc

- lib/id3c/cli/command/manifest.py
- lib/id3c/cli/io/google.py
The previous commit fixed how various metadata properties of a
Google doc are grabbed. Instead, just grab the etag since that's
all that's currently being used.
> Retrieve only etag detail from Google docs

- setup.py
With 4.7.0 deployed we get this error:
"No module named 'smartystreets_python_sdk.us_reverse_geo"
I was able to run the uw-reopening ETL locally with this version pinned. The lat/log lookup succeeded.
> Pin smartystreets-python-sdk at 4.6.1

- setup.py
Allows future releases while still excluding the known-bad release,
4.7.0.
SmartyStreets released 4.7.1 to fix the issue:
https://github.com/smartystreets/smartystreets-python-sdk/issues/23
> Relax dep on SmartyStreets SDK

- schema/deploy/receiving/clinical/indexes/processing-log.sql
- schema/deploy/receiving/consensus-genome/indexes/processing-log.sql
- schema/deploy/receiving/fhir/indexes/processing-log.sql
- schema/deploy/receiving/longitudinal/indexes/processing-log.sql
- schema/deploy/receiving/manifest/indexes/processing-log.sql
- schema/deploy/receiving/presence-absence/indexes/processing-log.sql
- schema/deploy/receiving/redcap-det/indexes/document-as-jsonb.sql
- schema/deploy/receiving/redcap-det/indexes/processing-log.sql
- schema/deploy/receiving/sequence-read-set/indexes/processing-log.sql
- schema/revert/receiving/clinical/indexes/processing-log.sql
- schema/revert/receiving/consensus-genome/indexes/processing-log.sql
- schema/revert/receiving/fhir/indexes/processing-log.sql
- schema/revert/receiving/longitudinal/indexes/processing-log.sql
- schema/revert/receiving/manifest/indexes/processing-log.sql
- schema/revert/receiving/presence-absence/indexes/processing-log.sql
- schema/revert/receiving/redcap-det/indexes/document-as-jsonb.sql
- schema/revert/receiving/redcap-det/indexes/processing-log.sql
- schema/revert/receiving/sequence-read-set/indexes/processing-log.sql
- schema/sqitch.plan
- schema/verify/receiving/clinical/indexes/processing-log.sql
- schema/verify/receiving/consensus-genome/indexes/processing-log.sql
- schema/verify/receiving/fhir/indexes/processing-log.sql
- schema/verify/receiving/longitudinal/indexes/processing-log.sql
- schema/verify/receiving/manifest/indexes/processing-log.sql
- schema/verify/receiving/presence-absence/indexes/processing-log.sql
- schema/verify/receiving/redcap-det/indexes/document-as-jsonb.sql
- schema/verify/receiving/redcap-det/indexes/processing-log.sql
- schema/verify/receiving/sequence-read-set/indexes/processing-log.sql
See commit messages for all the deets.
After deploy, the following should be manually run to clean up my rogue index:
```
drop index receiving.redcap_det_document_jsonb_idx__trs_20200323;
```
> Receiving indexes

- lib/id3c/cli/command/__init__.py
- lib/id3c/cli/command/etl/redcap_det.py
- lib/id3c/cli/command/geocode.py
Here are some commits I did awhile ago as part of a bigger picture to lock the cache file within python (instead of relying on a user to create file lock on the cache at runtime).
These commits alone may be enough to ease up on some of the constraint on our system -- that is, by using different caches for different ETL jobs, we can allow some jobs to run concurrently.
> Configurable cache

- lib/id3c/api/utils/routes.py
- lib/id3c/db/session.py
During local testing, I noticed that connections were held open
even after requests.
Based on inspecting the reference count of "session" after calling
"route", this does *not* appear to be a case of a circular reference
causing the session/connection to never reach a reference count of zero
and thus never be destroyed.
I suspect it happens because object destruction (__del__) does not
always happen immediately upon the reference count reaching zero (and
sometimes does not happen at all).
In any case, explicitly closing connections when you're finished is best
practice anyway.  This makes it clear that the session is not (and
should not be) used afterwards and immediately frees the related
database server resources.
It doesn't appear that the lingering connections occur in production, …
> api: Explicitly close DatabaseSession at request end

- lib/id3c/cli/command/etl/presence_absence.py
Each sample has a top level key "sampleFailed" that is marked True if
the entire sample has been marked as failed. We need to inspect this
top level key because the individual target results do not reflect this
failure status.
ID3C currently does not model failed presence/absence results,
so skip all results if the sample is failed at this top level.
> etl presence-absence: skip samples that have been marked as failed

- Pipfile.lock
- lib/id3c/cli/command/__init__.py
- setup.py
When we did `pipenv update` last week, some dependencies were updated and caused problems in production.
This PR addresses the pandas and fhir.resources changes as described in the commit messages.
I created a Trello card to migrate to fhir.resources version 6.
> ID3C dependency updates

- lib/id3c/cli/redcap.py
Set the exportSurveyFields parameter to true when fetching records
from REDCap so that for surveys, the {survey_name}_identifier and
{survey_name}_timestamp fields are returned.
> Add exportSurveyFields parameter when fetching records

- lib/id3c/cli/command/redcap_det.py
- lib/id3c/cli/redcap.py
Switches `id3c redcap-det generate` to use the new-style env vars for API credentials and significantly reduces the amount of data transferred over the wire in the API requests.
See commit messages for details.
> REDCap DET generation

- lib/id3c/labelmaker.py
Add the barcode layouts for the Apple respiratory study, the public schools
study, and the Adult Family Home outbreak / Workplace outbreak projects.
> Add barcode layouts for some Year 3 projects

- lib/id3c/cli/redcap.py
Allows the import into the UW EH&S reporting project to use this method
instead of rolling its own API call.
> redcap: Support different date formats when updating records

- lib/id3c/cli/redcap.py
Several of REDCap's API methods take a "data" parameter to upload
record or user information.  We don't want to include this in logs due
to privacy/PII concerns as well as exceeding syslog message sizes.
Masking is the same approach we take in id3c.db.session.pg_environment().
> redcap: Mask data being send to the REDCap API when logging request parameters

- lib/id3c/labelmaker.py
We now have two collection sets for the schools testing study. Use the same naming convention used for the UW Reopening study--"home" and "observed".
I minted and made labels locally. "SCHOOL TESTING OBSERVED <barcode>" does just fit onto the current label. Nothing gets truncated for home or observed.
> Update labelmaker with school testing labels

- lib/id3c/cli/redcap.py
Add additional methods to our redcap `Project` class to support different functionality we use in the [backoffice](https://github.com/seattleflu/backoffice) repo.
Methods include
* report
* metadata
* update_metadata
* users
* update_users
> Redcap dal

- lib/id3c/cli/command/etl/presence_absence.py
Update the presence-absence ETL to check a target's clinical status
(`clinicalStatus`).
Per @joverlee521:
Individual targets of the OpenArray will be CLIA validated (~mid
January 2021?). We will be receiving target.clinicalStatus that
indicates whether or not a result is "Clia" or "Research". We need
to ingest this key for individual results so that we can return
SARS-CoV-2 OpenArray results when it gets validated.
Release plan:
1. Samplify send OA results with sample.assayType = "Research" (no
changes to ID3C ETL required)
2. Samplify adds target.clinicalStatus to the JSONs for both OA and
qPCR
3. ID3C updates ETL to ingest target.clinicalStatus instead of the
sample.assayType
4. Samplify removes the sample.assayType key
Ideally all steps are completed before the OA SARS-CoV-2 is …
> etl presence-absence: Check target clinicalStatus

- lib/id3c/cli/command/etl/manifest.py
We forgot to add the collection sets for the new studies to the
manifest ETL. As a result, samples with them are being skipped.
> Add collection sets for new studies to Manifest ETL

- lib/id3c/cli/redcap.py
Most lines already included the project info.
This is helpful when reading logs for a process that accesses multiple
REDCap projects.
> redcap: Include the project in two log lines which were missing it

- lib/id3c/cli/io/google.py
In the `files().get` call to get the metadata for a Google Drive document
specify supportsAllDrives=True. SFS has moved content into a shared
Google Drive, and without this parameter set to True we get a 404
error.
From https://developers.google.com/drive/api/v2/reference/files/get:
"Whether the requesting application supports both My Drives and shared
drives. (Default: false)"
> Use supportsAllDrives when getting Google metadata

- setup.py
Running with 4.8.0 deployed in production is giving this error:
"File "/opt/backoffice/id3c-production/.venv/lib/python3.6/site-packages/smartystreets_python_sdk/client_builder.py"
, line 6, in <module> from smartystreets_python_sdk.us_autocomplete_pro import Client as
USAutocompleteProClient ModuleNotFoundError: No module named
'smartystreets_python_sdk.us_autocomplete_pro'"
Pin a version < 4.8.0 for now.
> Pin smartystreets version to < 4.8.0

- lib/id3c/labelmaker.py
Setting up the most commonly used layout settings for now for the yakima schools study.
This would be great to follow up with a refactor to allow an arg to `id3c identifier mint` that allows override of the layout's default `copies-per-barcode`
> Add layout for yakima schools testing to labelmaker

- lib/id3c/cli/command/identifier.py
- lib/id3c/labelmaker.py
When minting barcodes or printing labels, use the `--copies-per-barcode`
option to specify how many copies per barcode should be included in the
printable barcode labels.
NOTE: This is a naive overwrite of the default number. It does not take
into account the specific layout for better UX that may require blanks.
For example, changing the copies per barcode for the "samples" barcodes
can result in a confusing layout in the PDF.
> identifier/labelmaker: add --copies-per-barcode option

- lib/id3c/cli/command/geocode.py
SmartyStreets Python API throws an error when given an empty or
whitespace-only string.  Even if it didn't, there's no point in making a
request for an empty address.
Fixes an error we observed in production in the ETL for metadata about
UW residual samples.
> geocode: Avoid extracting addresses from empty or whitespace-only strings

- lib/id3c/cli/command/etl/manifest.py
Manifest record id is being added to logged warnings to make it easier to locate the record
during debugging and inform the lab of which record needs troubleshooting.
> Add record id to logged warnings in manifest etl

- Pipfile.lock
- mypy.ini
- setup.py
After prior deployment that updated click to version 8.0.1, ETLs started
encountering issues. They continued to run without error, but changes were
rolled back inexplicably. This is possibly related to change in click
flag_value typing [#1886](https://github.com/pallets/click/issues/1886).
Confirmed with local testing that rolling back to version 7.1.2 resolved
the problem. Pinning click to 7.x while investigating further and making
required code changes to upgrade to 8.x.
> Pinning click to version 7.x

- .gitignore
A pyproject.toml file is auto-generated when using pipenv>=2020.11.15. Adding
it to .gitignore out of an abundance of caution, to avoid having it deployed until
production is upgraded to pipenv>=2020.11.15 but allowing us to use those versions
of pipenv locally.
> Add pyproject.toml to .gitignore

- tests/sqitch-transactions.py
Deploy and revert scripts must use a final commit and no other premature
commits.  Verify scripts must use a final rollback and no other
premature rollbacks.  All scripts must start with begin.
This test was written to catch future instances of actual mistake made
in our shipping/views change in the id3c-customizations repo.  The
possibility for the same mistake exists in this repo too.
> Tests: Check that our Sqitch changes use transactions properly

- lib/id3c/cli/command/etl/fhir.py
- lib/id3c/cli/command/etl/manifest.py
Add the new UW identifier set collections-uw-tiny-swabs to the expected
sets for the FHIR and manifest ETLs.
Note: we didn't ingest data from the tiny swabs pilot, this is preparation
for when we start using that identifier set for the HCT redcap project
> etl: Add new UW id set to FHIR and manifest ETLs

- lib/id3c/api/__init__.py
- lib/id3c/api/datastore.py
- lib/id3c/api/routes.py
- lib/id3c/api/static/index.html
- lib/id3c/api/utils/routes.py
- lib/id3c/json.py
- setup.py
Refresh of [a long-standing WIP](https://github.com/seattleflu/id3c/compare/wip/identifier-api) from a couple years ago to add an identifier API. It had slightly different but overlapping motivations at the time. I refreshed it on the latest code and added an identifier lookup endpoint which could be used for validation.
Marked as draft because I expect we'll want some further consideration first. We don't have to use this as-is, but I figured it could be a starting point for discussion about what we do want there with much of the plumbing done.
Commit messages contain details.
> Web API for identifiers and identifier sets

- tests/sqitch-plan.py
Tags are how Sqitch enables reworking of changes (such as our
shipping/views change) and are intended to mark the point when a schema
is "released" and thus existing change scripts can't be edited in place;
instead adding a new change or rework is necessary.
In our case, we "release" our schema when we deploy it to production,
and we typically deploy to production on every merge to master.  This
means we very rarely have periods where a tag isn't necessary, so
require one via our CI tests.
> Tests: Check that on master the Sqitch plan always ends with a tag

- lib/id3c/cli/command/geocode.py
- setup.py
This is sometimes necessary if more than one license/plan is associated
with an account.  The default behaviour is unchanged.  Requires a
version bump on the SmartyStreets SDK dep, as the license handling was
only added in 4.6.0.
I made this change while making other changes to locally test
SmartyStreets' new "enhanced" lookups.  This knob can be necessary to
resolve ambiguity when there are multiple subscriptions active, which
seems like a situation that could easily arise at some point in
production, as it's determined by our SmartyStreets account, not
anything we deploy.  It'd be nice for it to already exist before its
needed to fix a broken system!
> geocode: Support specifying explicit SmartyStreets licenses to use

- lib/id3c/api/datastore.py
- lib/id3c/api/routes.py
- lib/id3c/api/static/index.html
- lib/id3c/cli/command/identifier.py
- lib/id3c/db/__init__.py
- schema/deploy/warehouse/identifier-set-use.sql
- schema/deploy/warehouse/identifier-set-use/data.sql
- schema/deploy/warehouse/identifier-set/use-not-null.sql
- schema/deploy/warehouse/identifier-set/use.sql
- schema/deploy/warehouse/identifier/indexes/identifier_set_id_btree.sql
- schema/revert/warehouse/identifier-set-use.sql
- schema/revert/warehouse/identifier-set-use/data.sql
- schema/revert/warehouse/identifier-set/use-not-null.sql
- schema/revert/warehouse/identifier-set/use.sql
- schema/revert/warehouse/identifier/indexes/identifier_set_id_btree.sql
- schema/sqitch.plan
- schema/verify/warehouse/identifier-set-use.sql
- schema/verify/warehouse/identifier-set-use/data.sql
- schema/verify/warehouse/identifier-set/use-not-null.sql
- schema/verify/warehouse/identifier-set/use.sql
- schema/verify/warehouse/identifier/indexes/identifier_set_id_btree.sql
Identifier type (sample, collection, clia, etc.) is missing from the data
model, currenly only  encoded through identifier_set naming convention. Adding
it to identifier_set makes it more explicitly defined which will simplify
implementations of API and ETL functions and allow for future migration away
from using multiple identifier columns in sample table.
> Add use column to identifier_set

- lib/id3c/cli/command/etl/__init__.py
- lib/id3c/cli/command/etl/enrollments.py
- lib/id3c/cli/command/etl/fhir.py
- lib/id3c/cli/command/etl/manifest.py
- lib/id3c/db/__init__.py
The `upsert_sample` function is implemented in three different places. This
consolidates those to a single standardized version of the function to reduce
redundancy. Also updates existing `upsert_sample` function calls to match the
new definition, as well as some minor code clean up.
This function is also being moved out of the `id3c.cli.command.etl` subpackage to
`id3c.db` in anticipation of also using it for a API development. Other "upsert"
functions are currently located in `etl/__init__.py` but are currently only used in
`etl` modules, whereas `db` contains more generic functions/classes used in `id3c.api`
and `id3c.cli`.
> Consolidate upsert_sample function

- lib/id3c/labelmaker.py
Adding labelmaker layouts for two new identifier sets that were
added for UW tiny swabs: home and observed.
"UW TINY O" was used as label to indicate barcodes from observed set, and
"UW TINY U" was used for unobserved (home) set. This will also differentiate
them from the barcode labels from the pilot study, which used "UW TINY".
> Add label formats for UW tiny swabs home and observed sets

- Pipfile.lock
- lib/id3c/api/datastore.py
- lib/id3c/api/routes.py
- lib/id3c/api/static/index.html
- mypy.ini
- setup.py
Add verify-barcode-use endpoint to API for use with Laboratory Information
Management System (LIMS) and/or other system integration, for automation of QC processes.
This endpoint takes a JSON array of objects as input, with each object containing a barcode
and its associated use type to verify (i.e. `sample`, `collection`, `clia`). The response
will be a JSON array of the same objects with boolean values for `barcode_found` to indicate
whether the barcode exists in ID3C and `use_match` to indicate whether the input use type
matches what is stored in ID3C.
> Add verify/barcode-uses endpoint to API

- schema/deploy/roles/sample-editor/create.sql
- schema/deploy/roles/sample-editor/grants.sql
- schema/revert/roles/sample-editor/create.sql
- schema/revert/roles/sample-editor/grants.sql
- schema/sqitch.plan
- schema/verify/roles/sample-editor/create.sql
- schema/verify/roles/sample-editor/grants.sql
Initially for use with LIMS, this role will be used to insert and
update records in the `warehouse.sample` table as well as verify
barcodes and uses in `warehouse.identifier` and `identifier_set` tables
via ID3C API.
> Add sample editor role to database

- lib/id3c/api/datastore.py
Date should be included in `warehouse.sample` jsonb column `details`.
Adding here to match process in manifest ETL and ensure this value
is present for queries (and alerts) that rely on it.
> Add date to sample API to be written to details

- lib/id3c/api/datastore.py
The manifest ETL renames the `clia_id` from worksheet to `clia_barcode` before storing
in sample details. Updating API endpoint here to match, so that data submitted
through the API matches format of data previously ingested from the manifest worksheets.
The `clia_barcode` key name is also used in shipping views so this will ensure it
is populating correctly there and will appear in related automated Slack alerts.
> Rename CLIA ID in sample details to match existing data

- lib/id3c/cli/command/etl/__init__.py
A new value `covid_screen` is being ingested from SCH Clinical data that
identifies samples that were collected for screening purposes only.
This error will initially be used in clinical ETL of id3c-customizations
for cases of unexpected values.
> Add error class for use in id3c-customizations clinical ETL

- lib/id3c/cli/command/etl/fhir.py
- lib/id3c/cli/command/etl/manifest.py
- lib/id3c/cli/command/etl/presence_absence.py
- lib/id3c/labelmaker.py
To support the new tiny swab format for the following studies, SCAN, Adult Family Homes, and Workplace:
1. their barcode layout is added to labelmaker.py
2. their identifiers is added to the presence_absence ETL
> Add Tiny SCAN, AFH, and Workplace Identifier Sets

- lib/id3c/api/datastore.py
- lib/id3c/api/routes.py
- lib/id3c/api/static/index.html
Provides ability to retrieve sample records using a GET request which
will be useful in conjunction with the `warehouse/sample` POST endpoint,
to view records before and after updating them through the API.
> Adding sample GET endpoint to API

- lib/id3c/cli/redcap.py
A 300 second timeout is being added to all REDCap requests, which ultimately
all use the _fetch function. It has been confirmed there is 120 second timeout on the
server side so this should be plenty of extra time before giving up on a request.
The goal of this change is to prevent requests from hanging indefinitely, and to
throw an exception when a request exceeds 5 minutes.
> Add timeout to REDCap requests

- lib/id3c/cli/command/geocode.py
Setting address['secondary'] field to a blank string will sometimes
return a valid address when the original lookup failed. These changes
preform address lookups via the us_street_lookup() and extract_address()
with address['secondary'] = '' after a failed lookups for both the
above methods with the original `secondary` field.
> Lookup address without secondary address field (appartment number)

- lib/id3c/cli/command/__init__.py
- lib/id3c/cli/command/etl/redcap_det.py
- lib/id3c/cli/command/geocode.py
Changes to make it more difficult to use SmartyStreets credits during local development. This has occurred multiple times while testing REDCap DET ETL processes locally, causing unnecessary usage.
The geocoding cache file will now be required, and will fail if the specified file is not found. The other change is that the user will be prompted prior to any requests being sent to the SmartyStreets API, if geocoding in a non-production environment. This will help ensure that use of the geocoding service during local development is more visible and intentional.
> Prevent local smartystreets usage

- lib/id3c/cli/redcap.py
Currently, the only way to update one or more records is using
update_records() in the Project class. The new update_record() function
updates only the record used to construct the Record object. Adding the
"record_id" and "redcap_event_name" keys/values to the record
parameter is optional.
> Added update_record() to the Record class in redcap.py

- lib/id3c/labelmaker.py
In anticipation of the new study, FH Prospective Sero Study AIM 3B, the identifier set 'collections-airs' is added.
Changes were tested via 'dry-run' and output file was expected based on the specs of the study's requester.
UPDATE: Study's requester has confirmed that the barcode minted is what they want visually.
> Add Fred Hutch AIRS Identifier Set

- Pipfile.lock
- setup.py
Previously, `mypy` was pinned to version 0.910 due to an incompatible type
error that started appearing during CI tests running on github. This issue
is being resolved with a code change in `id3c-customizations`
(https://github.com/seattleflu/id3c-customizations/pull/278) which allows
us to upgrade to the latest version of `mypy` without any tests failing.
> Unpin mypy package version

- Pipfile.lock
- setup.py
This package was previously pinned to v2.24.0 because a bug was
introduced in v2.25.0. That bug was fixed in version 2.26.1:
https://github.com/googleapis/google-api-python-client/releases/tag/v2.26.1, so it
is now safe to upgrade to the latest version (tested with v2.35.0).
> Unpinning google-api-python-client version

- .gitignore
Newer versions of pipenv create a build folder, which can be ignored.
> Update .gitignore to ignore build folder

- lib/id3c/labelmaker.py
In anticipation of the Cascadia study, this change adds the
identifier set `collections-cascadia-tiny-swabs-home`. Because
this set uses duplicate tiny barcodes, this collection set
inserts a blank barcode before each 4th barcode to keep the
last column empty and duplicate barcodes next to each other.
This change was tested locally by doing a dry run of minting barcodes for the new identifier, which output barcodes in the correct format (51 pairs of duplicates per sheet, with the last column blank, for a total of 1,020 barcodes per 20 sheets).
Update: Barcodes were tested and printed and look good to the requesters.
> Add Cascadia Identifiers Set

- lib/id3c/cli/command/etl/__init__.py
Related to ingesting additional Seattle Children's fields, `admit_to_icu` and `admit_during_this_encounter` and convert response to `yes` or `no`.
Refer to id3c-customization': https://github.com/seattleflu/id3c-customizations/pull/283
> SCH Retro Additional Fields/Values Ingestion

- .gitignore
- bin/.gitignore
- dev/doc/.gitignore
- docs/.gitignore
- lib/.gitignore
- lib/id3c/.gitignore
- schema/.gitignore
- schema/deploy/.gitignore
- schema/revert/.gitignore
- schema/templates/.gitignore
- schema/verify/.gitignore
- tests/.gitignore
Reworking of .gitignore files to exclude everything up front, with
exceptions for files and folder that should be included. This is to
reduce the chance of pushing any files unintentionally.
> Rework gitignore to function as allowlist

- Pipfile.lock
- lib/id3c/cli/command/manifest.py
- lib/id3c/cli/io/pandas.py
- setup.py
Update pandas to 1.4.1. 
This also requires some changes in the specimen manifest parsing code, because pandas has changed the way it handles missing values in strings. I almost suspect this is a bug in pandas, because of the way it breaks things. Consider the following code:
```
import pandas as pd
print(pd.__version__)
d = {'c1': ['foo', 'bar', None]}
df = pd.DataFrame(data=d, dtype='string')
print(df.dtypes)
print(df.apply(lambda c: c.str.strip().replace({pd.NA: None}).replace({"": None, "na": None})))
```
This mirrors the way the specimen manifest-parsing code does a replacement of missing values around [line 334](https://github.com/seattleflu/id3c/compare/seidelma/bugfix/pandas14?expand=1#diff-4f914815f7f16734ccfb03bedcc1104bba4dfe3cef528b2e28022fd4109ad1f5L334).
With Pandas 1.1.5, …
> Update pandas to 1.4.1

- lib/id3c/api/schemas.py
- lib/id3c/api/static/index.html
To be able to accept aliquot and rack C values in sample POST requests,
the JSON schema is being updated to include the `aliquot_c`, `rack_c` and
`rack_c_nickname` attributes. These will then be included in arrays with
the corresponding A and B values to be stored in `sample.details`.
> Add aliquot C and rack C fields to sample JSON schema

- lib/id3c/cli/command/etl/__init__.py
When comparing two items with data type `row`, the presence of a null element
within either row will return null rather than the expected boolean. This was
resulting in old encounter records continuing to be updated even though the data was not changing.
To avoid this behavior, the rows are being cast to text before comparing them.
> Cast rows to text for data comparison in upsert_encounter

- lib/id3c/cli/io/pandas.py
Adding an new argument to the `dump_ndjson` function to mask columns that
may contain sensitive data, to be used during development and testing. If no value is
passed, the default will be to keep all columns unmasked.
The `mask_values` function is being added here for this purpose, but can also be used
independently if masking is needed on a dataframe that is not being dumped to ndjson.
> Add optional argument to dump_ndjson for masking columns

- lib/id3c/db/__init__.py
Changes to the encounter_id linked to each sample may indicate an issue with the source
data, ETL, or the result of corrections being made on the source. This results in encounter
records that had previously been linked to samples to no longer be, which could indicate they
are no longer valid and can be deleted.
Adding logging at debug level to monitor how often this occurs during normal operations.
If it's reasonably low, this may be elevated to warning level. If it's occurring more
often than expected, it will require some additional investigation.
> Log changes to encounter_id when updating sample records

- lib/id3c/cli/command/geocode.py
Using try/catch will surface a key error if an address is not in the cache.
Normally this isn't a problem, but if another exception occurs while in
the `catch` segement of an address not being in the cache the key will get
logged out. Since this key is an address, there is therefore the potential
that this address is logged on geocoding failure. This change will prevent
the actual address from being logged if there is a geocoding failure.
> Use `cache.keys()` to cache addresses rather than Try/Catch

- lib/id3c/cli/command/etl/__init__.py
When I deployed this previously I deployed with a misnamed key in one of the SQL commands.
> Fix misnamed key in `upsert_location`

- Pipfile.lock
- lib/id3c/cli/command/etl/presence_absence.py
- setup.py
The presence-absence ETL failed due to an incorrectly formatted timestamp
which had 9 decimal places instead of the 6 that it was expecting. Using
parser from dateutil handles varying number of decimal places on the seconds
value.
> Handle nanoseconds in timestamp values

- lib/id3c/cli/command/etl/__init__.py
The `upsert_presence_absence` function is being updated in line with the other
upsert functions, to prevent gaps in the sequence used for `presence_absence_id` and
avoid unneccessary updates when data has not changed.
Also adding warning-level logs for non-typical changes to `presence_absence` records which
may require further investigation (changing `present`, `sample_id`, or `target_id` values).
> Rework upsert presence_absence function

- lib/id3c/db/__init__.py
upsert_sample can allow identifiers to change for a given sample.
It should be rare that a sample identifier or collection identifier
is changed from one non-null value to another. When this happens,
log a warning so that we can confirm with the data source (typically,
the lab) that this change was intended. And if so, we can do any
manual cleanup as necessary for participants results or linelist
reporting, for example.
> Warn when sample identifiers are changed during upsert

- lib/id3c/db/__init__.py
- schema/deploy/functions/mint_identifiers.sql
- schema/deploy/roles/identifier-minter/grants@2022-07-25.sql
- schema/revert/functions/mint_identifiers.sql
- schema/revert/roles/identifier-minter/grants.sql
- schema/revert/roles/identifier-minter/grants@2022-07-25.sql
- schema/sqitch.plan
- schema/verify/functions/mint_identifiers.sql
- schema/verify/roles/identifier-minter/grants@2022-07-25.sql
A `mint_identifiers` function is being added to improve performance of identifier
minting by handling more of the process in postgres and less in python. The function
will generate uuids and check the hamming distance of the last 8 characters against
all existing barcodes. It will continue trying new identifiers until the distance check
passes, at which point it will insert a record into the identifier table. The function will repeat
this process until it has reached the indicated `number_to_mint` and returns the records that
were inserted.
> Add `mint_identifiers` function to improve performance

- Pipfile.lock
- setup.py
Xlrd was previously pinned to version = 1.2.0 because of security vulnerabilities that prevented it from parsing new xlsx files. Openpyxl now handles these files and xlrd handles .xls files. Pandas requires xlrd >= 2.1.0 now, which we didn't have because it could cause issues parsing certain barcodes. Now that we've transitioned away from aliquoting sheets, we only parse excel files for retrospective data.
This package upgrade was tested on SCH, PHSKC, and UW retros data. For SCH data, problematic barcodes parsed the same on 1.2.0 and 2.1.0. For PHSKC data, there was no diff between the production ndjson output on xlrd 1.2.0 and my local output on xlrd 2.1.0. Likewise, there was no diff between the prod uw retro ndjson generated with xlrd 1.2.0 and my local ndjson generated with xlrd …
> Unpin xlrd and upgrade to latest version

- lib/id3c/cli/command/etl/consensus_genome.py
- lib/id3c/cli/command/etl/enrollments.py
Tagging enrollments and consensus genome ETLs as deprecated. These are no longer in use and have cron jobs disabled.
> Tag deprecated ETL modules

- lib/id3c/labelmaker.py
Lab will now occasionally ask for sample barcodes in single formation rather than in duplicate formation. This change formalizes this request and allows minting users to specify the single format when minting sample barcodes. The duplicate format remains the default sample barcode format.
> Add a new `singlet` Format for Sample Barcodes

- lib/id3c/labelmaker.py
The label maker API has moved to a new location. Updating to use the new location by default going forward.
> Update default label API URL

- Pipfile.lock
- lib/id3c/cli/command/geocode.py
- lib/id3c/logging/filters.py
Use of the input function with message string, and/or print function causes issues when geocoding function is used as part of a process that is using dump_ndjson and redirecting stdout to a file. To avoid having the input prompt text message included in stdout, it's being moved to a logging message.
> Use logging to print promts for input

- lib/id3c/cli/command/redcap_sync.py
Fix for #323 to only send slack messages if there are records which might need to be deleted.
> Only Send Slack Message if Deletions Exist

- lib/id3c/api/datastore.py
- lib/id3c/api/schemas.py
- lib/id3c/api/static/index.html
- lib/id3c/db/__init__.py
Updates to warehouse/sample POST endpoint to allow `access_role` value to be passed. A database constraint will ensure this value is set correctly based on the `sample_origin` which can be used to identify data from a project that should have restricted access.
> Sample API update
