lib/seattleflu/db/cli/command/manifest.py
Some values are whitespace-only, which leads to processing issues later
on in the ETL routine because a whitespace-only string is truthy.  It
seems best to handle this on the parsing side and standardize the JSON
records as much as possible.
This fixes an observed downstream data loading issue.
=> manifest parse: Strip leading/trailing whitespace from values

lib/seattleflu/db/cli/command/etl/clinical.py, lib/seattleflu/db/cli/command/preprocess.py, schema/deploy/roles/clinical-processor/create.sql, schema/deploy/roles/clinical-processor/grants.sql, schema/deploy/roles/clinical-uploader/create.sql, schema/deploy/roles/clinical-uploader/grants.sql, schema/revert/roles/clinical-processor/create.sql, schema/revert/roles/clinical-processor/grants.sql, schema/revert/roles/clinical-uploader/create.sql, schema/revert/roles/clinical-uploader/grants.sql, schema/sqitch.plan, schema/verify/roles/clinical-processor/create.sql, schema/verify/roles/clinical-processor/grants.sql, schema/verify/roles/clinical-uploader/create.sql, schema/verify/roles/clinical-uploader/grants.sql
Implement clinical code review requested changes
from pull request #8.
Co-author: Jover Lee <joverlee521@gmail.com>
=> Create new database automation users for clinical pipeline and refactor pipeline code for readability

lib/seattleflu/db/cli/command/etl/clinical.py, lib/seattleflu/db/cli/command/preprocess.py
We are now receiving `census_tract` in the SCH clinical data :tada:.
In this latest clinical data pull from SCH, several column names were
also changed. The expected column names have been modified in this
commit.
=> Update clinical preprocess for SCH data

lib/seattleflu/db/cli/command/etl/clinical.py, lib/seattleflu/db/cli/command/preprocess.py
This is a cherry-picked version of PR #18.
=> Clinical preprocess refactor

schema/deploy/roles/identifier-minter/create.sql, schema/deploy/roles/identifier-minter/grants.sql, schema/deploy/warehouse/identifier/triggers/barcode-distance-check.sql, schema/deploy/warehouse/identifier/triggers/barcode-distance-check@2019-05-31-identifier-minter.sql, schema/revert/roles/identifier-minter/create.sql, schema/revert/roles/identifier-minter/grants.sql, schema/revert/warehouse/identifier/triggers/barcode-distance-check@2019-05-31-identifier-minter.sql, schema/sqitch.plan, schema/verify/roles/identifier-minter/create.sql, schema/verify/roles/identifier-minter/grants.sql, schema/verify/warehouse/identifier/triggers/barcode-distance-check@2019-05-31-identifier-minter.sql
Creates an identifier-minter role in the database via sqitch.
=> Create identifier-minter role

lib/seattleflu/db/cli/command/__init__.py, lib/seattleflu/db/cli/command/clinical.py
https://trello.com/b/MFOJfX46/sfs-tasks
https://trello.com/c/oYB01LHh/121-rename-preprocess-command-to-clinical (addressed in PR #23).
This PR lives as a separate one from #23 for consistency with Trello. It felt a little like overkill but I wanted to err on the side of preferring more organization.
=> Split clinical preprocess into parse and upload steps

schema/deploy/shipping/views.sql, schema/deploy/shipping/views@2019-06-04-join-shipping-views.sql, schema/revert/shipping/views@2019-06-04-join-shipping-views.sql, schema/sqitch.plan, schema/verify/shipping/views@2019-06-04-join-shipping-views.sql
Adds new shipping view that joins the
incidence_modeling_observation_v2 view with the
presence_absence_results_v1 view.
=> Add new join view

lib/seattleflu/db/cli/command/clinical.py
Perform quality control on `parse-sch` like we're doing in `parse-uw`.
=> Add barcode qc check for sch clinical data

schema/deploy/roles/longitudinal-processor/create.sql, schema/deploy/roles/longitudinal-processor/grants.sql, schema/deploy/roles/longitudinal-uploader/create.sql, schema/deploy/roles/longitudinal-uploader/grants.sql, schema/revert/roles/longitudinal-processor/create.sql, schema/revert/roles/longitudinal-processor/grants.sql, schema/revert/roles/longitudinal-uploader/create.sql, schema/revert/roles/longitudinal-uploader/grants.sql, schema/sqitch.plan, schema/verify/roles/longitudinal-processor/create.sql, schema/verify/roles/longitudinal-processor/grants.sql, schema/verify/roles/longitudinal-uploader/create.sql, schema/verify/roles/longitudinal-uploader/grants.sql
Create an automation user for running longitudinal processes on the server.
=> Create automation user for etl longitudinal

lib/seattleflu/db/cli/command/__init__.py, lib/seattleflu/db/cli/command/clinical.py, lib/seattleflu/db/cli/command/etl/clinical.py, lib/seattleflu/db/cli/command/longitudinal.py
This PR adds to the `clinical` and `etl clinical` processes. 
There is no need for schema changes.
=> Ingest kaiser permanente data

.travis.yml, dev/show-help, lib/seattleflu/api/datastore.py, lib/seattleflu/api/exceptions.py, lib/seattleflu/api/utils/__init__.py, lib/seattleflu/api/utils/routes.py, lib/seattleflu/db/__init__.py, lib/seattleflu/db/cli/command/__init__.py, lib/seattleflu/db/cli/command/etl/__init__.py, lib/seattleflu/db/cli/command/etl/clinical.py, lib/seattleflu/db/cli/command/etl/consensus_genome.py, lib/seattleflu/db/cli/command/etl/enrollments.py, lib/seattleflu/db/cli/command/etl/kit.py, lib/seattleflu/db/cli/command/etl/longitudinal.py, lib/seattleflu/db/cli/command/etl/manifest.py, lib/seattleflu/db/cli/command/etl/presence_absence.py, lib/seattleflu/db/cli/command/identifier.py, lib/seattleflu/db/cli/command/longitudinal.py, lib/seattleflu/db/cli/command/manifest.py, lib/seattleflu/db/cli/command/reportable_conditions.py, lib/seattleflu/db/cli/command/sequence_read_set.py, lib/seattleflu/db/types.py, mypy.ini
Figuring that this wasn't going to ever get priority otherwise, I just plowed through all our outstanding type check errors today. Most changes are to the type annotations and so shouldn't have functional effects on the code, but some functional changes were necessary (and some bugs were caught by mypy! :-). `./dev/mypy` now reports no problems and Travis CI is configured to test this going forward, to keep us honest.
=> Fix all outstanding type check errors

lib/seattleflu/db/cli/command/reportable_conditions.py
Change the `reportable-conditions notify` routine to perform additional
steps when a sample is missing a linked site.
If the site is missing from a sample encounter, look in the manifest
data and relay workbook and sheet name in the Slack notification.
=> reportable-conditions: improve logic for null site

schema/deploy/roles/consensus-genome-processor/grants@2019-09-30.sql, schema/revert/roles/consensus-genome-processor/grants.sql, schema/revert/roles/consensus-genome-processor/grants@2019-09-30.sql, schema/sqitch.plan, schema/verify/roles/consensus-genome-processor/grants@2019-09-30.sql
This should stop the error alerts we are getting in slack regarding `etl consensus-genome`.
We added update to segment in the consensus genome etl
but forgot to grant permissions to update segment to the
consensus-genome-processor role.
=> Fix: update consensus-genome-process grants

schema/deploy/shipping/views@2019-10-16.sql, schema/revert/shipping/views.sql, schema/revert/shipping/views@2019-10-16.sql, schema/sqitch.plan, schema/verify/shipping/views@2019-10-16.sql
Add organism column to `shipping.observation_with_presence_absence_result_v1`
=> Update observation with presence absence v1

lib/id3c/cli/command/__init__.py, lib/id3c/cli/command/etl/__init__.py, lib/id3c/cli/command/etl/clinical.py, lib/id3c/cli/command/etl/consensus_genome.py, lib/id3c/cli/command/etl/enrollments.py, lib/id3c/cli/command/etl/kit.py, lib/id3c/cli/command/etl/longitudinal.py, lib/id3c/cli/command/etl/manifest.py, lib/id3c/cli/command/etl/presence_absence.py, lib/id3c/cli/command/etl/redcap_det.py, lib/id3c/cli/command/redcap_det.py, lib/id3c/cli/command/sequence_read_set.py, lib/id3c/cli/redcap.py
Incorporates #73 + some additional robustness around standardizing race. I expect more work will be done here as we review/integrate our specific ETLs other than swab and send.
=> REDCap ETL

lib/id3c/labelmaker.py
We should figure out how to support labels in core better (so our custom needs can be in our extension) at some point in the future, but for now that's low priority and adjustments have to be made.
=> Labelmaker updates

dev/add-role, schema/deploy/roles/fhir-processor/create.sql, schema/deploy/roles/fhir-processor/grants.sql, schema/deploy/roles/redcap-det-processor/create.sql, schema/deploy/roles/redcap-det-processor/grants.sql, schema/revert/roles/fhir-processor/create.sql, schema/revert/roles/fhir-processor/grants.sql, schema/revert/roles/redcap-det-processor/create.sql, schema/revert/roles/redcap-det-processor/grants.sql, schema/sqitch.plan, schema/templates/deploy/role/create.tmpl, schema/templates/deploy/role/grants.tmpl, schema/templates/revert/role/create.tmpl, schema/templates/revert/role/grants.tmpl, schema/templates/verify/role/create.tmpl, schema/templates/verify/role/grants.tmpl, schema/verify/roles/fhir-processor/create.sql, schema/verify/roles/fhir-processor/grants.sql, schema/verify/roles/redcap-det-processor/create.sql, schema/verify/roles/redcap-det-processor/grants.sql
Necessary to setup automation here.
=> REDCap and FHIR ETL roles

lib/id3c/cli/command/etl/fhir.py, schema/deploy/warehouse/sample/null-identifiers-constraint.sql, schema/deploy/warehouse/sample/null-identifiers-constraint@2020-01-14.sql, schema/revert/warehouse/sample/null-identifiers-constraint@2020-01-14.sql, schema/sqitch.plan, schema/verify/warehouse/sample/null-identifiers-constraint.sql, schema/verify/warehouse/sample/null-identifiers-constraint@2020-01-14.sql
Details in commit messages and [Slack conversation](https://seattle-flu-study.slack.com/archives/CL1Q38ATG/p1578686532018400).
This will allow me to run the FHIR ETL in production.
=> FHIR ETL sample creation

schema/deploy/functions/date_or_null.sql, schema/revert/functions/date_or_null.sql, schema/sqitch.plan, schema/verify/functions/date_or_null.sql
This function casts a string to a date or returns null if the string is in an invalid datetime format.
~This function does not protect against dates that are out of range! Do we want it to?~
This function also returns null if a date is out of range i.e. `2020/01/50`
=> Add function `date_or_null`

lib/id3c/__init__.py, lib/id3c/data/logging-debug.yaml, lib/id3c/data/logging-default.yaml, lib/id3c/logging.py, setup.py
A slew of changes to logging to make it more configurable, plus a fix for [the urllib3 problem](https://trello.com/c/mB4AuRjY/330-fix-logging-config-so-that-geocoded-addresses-arent-debug-logged-by-urllib3).
=> Logging config

lib/id3c/cli/command/manifest.py
Avoids needing to add a new, study-specific option every time we need a
new column.  This was my intent from the start, but so far it's been
slightly more pragmatic to just add new options.
Requires config file changes in our specimen-manifests repo, which I've
prepared on a corresponding branch (seattleflu/specimen-manifests#10).
---
This is part of my prep for pushing up new retrospective samples to the UW retro REDCap project.
=> manifest: Genericize extraction of non-essential columns

lib/id3c/cli/command/identifier.py
Simple thing to avoid doing this manually.
=> identifier set: Add "create" command

lib/id3c/cli/command/etl/presence_absence.py
All of our data is long-since updated, so we no longer need this code
for backwards compatibility.
Removing the code also means we no longer care about the
samples[].targetResults[].id field in the received JSON documents.  This
is useful for NWGC as they want to start omitting it (or setting it to
null) for some results in the near future.
=> etl presence-absence: Remove upgrade path from old → new result identifiers

lib/id3c/cli/command/etl/presence_absence.py
These results come in a very similar JSON format, but lack a "chip" field which only applies to OpenArray.  In order to avoid confusing logic, the following decision table is used:
```
has results? | chip key exists? | chip is empty? | action  | comment                                                   |
-------------|------------------|----------------|---------|-----------------------------------------------------------|
yes          | yes              | no             | ingest  | normal p/a ingest                                         |
yes          | yes              | yes            | error   | Samplify bug                                              |
yes          | no               | -              | ingest  | non-OpenArray results, currently only in id3c-restricted  |
no …
```
=> etl presence-absence: Support ingestion of non-OpenArray results

lib/id3c/cli/command/etl/presence_absence.py
This field is being used for the results of CLIA-certified COVID-19
targets.  Other research-use-only targets continue to use
"targetResults".
Indeterminate/inconclusive results will be ingested with the "present"
column set to null, under the rationale that the presence known to be
uncertain/unknown.  These kind of results are typically because some
compound targets or target replicates are positive but some are
negative.  While the schema allows for "present is null", this is the
first time we're ingesting such data.
Several workflow states which aren't actual results are skipped during
ingestion.
Only the values "Positive", "Negative", and "Review" have been observed
so far, but the other possible values were communicated to us by NWGC.
It remains to be seen if those are accurate yet.
=> etl presence-absence: Handle new "sampleState" field

lib/id3c/cli/command/etl/presence_absence.py
Ingest new fields `assayName` and `assayDate`. Also added a bonus `extractionDate` field since I've seen that get mentioned on Slack as well.
=> New samplify fields

lib/id3c/cli/command/etl/presence_absence.py
Checks provided `assayType` is either "Clia" or "Research".
If no `assayType` is provided, then count the number of `wellResults`
to infer `assay_type`. 4 wells indicates "Clia" and everything else is
"Research". (added this assuming NWGC will not be resending everything)
=> etl presence-absence: Ingest `assayType` for p/a results

lib/id3c/cli/redcap.py
Using a custom subclass of dict lets us provide some custom attributes
like .project to point to the record's Project instance and .id to grab
the record's primary unique id (regardless of what it is named).
This is helpful when programmatically processing multiple projects that
share the same structure, for example with SCAN's project-per-language
setup.
=> redcap: Add a Record class (a subclass a dict)

lib/id3c/cli/command/etl/redcap_det.py
See details in commit messages.
Needs to be deployed with changes in ID3C-customizations (https://github.com/seattleflu/id3c-customizations/pull/134)
=> Support repeating REDCap

lib/id3c/labelmaker.py
Add layout for the Y3 Childcare study collection barcode sets.
=> labelmaker: Add layout for childcare study

lib/id3c/cli/command/etl/manifest.py, lib/id3c/cli/command/manifest.py
Do some light refactoring in the id3c manifest function and add doctests to verify output.
=> Refactor manifest

lib/id3c/cli/command/__init__.py, lib/id3c/cli/command/etl/redcap_det.py, lib/id3c/cli/command/manifest.py, lib/id3c/cli/command/redcap_det.py, lib/id3c/cli/redcap.py, lib/id3c/cli/utils.py, lib/id3c/db/datatypes.py, lib/id3c/db/session.py, lib/id3c/json.py, lib/id3c/url.py
Pushing a PR for these changes in advance of my PR for the priority queue command, as I believe they're mostly independently reviewable. Ok by me though if folks would rather wait to review both at the same time.
Details for these changes in the commit messages.
=> Changes to support our custom command processing the UW priority queue

lib/id3c/db/session.py, tests/web-api.py
=> Resolve ImportError when running id3c.api

lib/id3c/cli/redcap.py
For very large projects, such as our Husky Coronavirus Testing project,
paging allows record resultsets to fit within the memory/timeout
constraints of the API server.  REDCap seems to spool the whole
resultset (into memory?) before sending the response.  When constraints
are exceeded, we see HTTP 500 errors from the API.
---
This will enable fixing the UW EH&S export, by adding, e.g., `page_size = 5000` to the relevant `project.records(…)` call.
=> redcap: Support paged fetching of records

lib/id3c/db/__init__.py
This commit removes the logic in the `mint_identifiers` function that throws
an error if a maximum number of minting retries are hit. When we hit that
currently, we simply re-run the job. With this maximum retry limit removed,
the job will just keep retrying until it gets a valid barcode.
=> Remove retry limit for barcode minting

lib/id3c/cli/command/etl/redcap_det.py
Use new-style environment variables for REDCap API credentials. See commit message for more details.
**Note that deploying this PR will necessitate re-organizing our existing env vars to use the new style.** I think ideally this looks like combining all (or most) of the `id3c-production/env.d/redcap-*/` dirs into one new `id3c-production/env.d/redcap/` dir with a `REDCAP_API_TOKEN_…` file for each project and a shared `REDCAP_API_URL`. Other code/cronjobs will need adjustment too.
=> REDCap DET ETL tokens

lib/id3c/cli/io/pandas.py, lib/id3c/cli/redcap.py
A small grab bag of commits—see their messages for details—motivated by troubles with the UW EH&S report.
=> UW EH&S report support

lib/id3c/cli/redcap.py
Changes from a post-merge code review from #202.
=> Pr 202 post merge review

lib/id3c/cli/redcap.py, lib/id3c/json.py, lib/id3c/utils.py
I added context to JSON decoding errors for better troubleshooting of intermittent REDCap issues. Inspired by #217 but generalized a bit.
=> Better JSON decoding errors

lib/id3c/cli/command/manifest.py
While continuing to support one configuration entry per workbook, this change will allow
workbooks that share the same format to be entered as a list within a single entry. This
prevents needing to copy and paste the whole config (for example, when a new aliquoting
sheet is added), reducing the potential for errors and resulting in smaller YAML files.
Example YAML file:
```
---
workbooks:
- s3://fh-pi-bedford-t/seattleflu/bbi/2019_2020_sfs_aliquoting.xlsx
- s3://fh-pi-bedford-t/seattleflu/bbi/2019_2020_sfs_aliquoting_2.xlsx
- s3://fh-pi-bedford-t/seattleflu/bbi/2019_2020_sfs_aliquoting_3.xlsx
- s3://fh-pi-bedford-t/seattleflu/bbi/2019_2020_sfs_aliquoting_4.xlsx
- s3://fh-pi-bedford-t/seattleflu/bbi/2019_2020_sfs_aliquoting_5.xlsx
- …
```
=> Update manifest parse_using_config() to allow lists of workbooks

lib/id3c/json.py, lib/id3c/utils.py
Small improvements after noticing an oddity in our alerts.
Full details of changes in commit messages.
=> Improve JSON decoding errors

lib/id3c/labelmaker.py
Add LCRY-2380 size label format for UW tiny swabs - season 4 project.
=> labelmaker: Add layout for UW Tiny Swabs

lib/id3c/cli/redcap.py
REDCap API has a bug that incorrectly returns 200 status code and HTML
response text in HTML format containing an "unknown error" and "This may
have occurred if you have opened multiple browser tabs of the same REDCap
page". Requests that receive this reponse often succeed with additional
attempts.
This change will search for that specific response and retry
the request up to 10 times before proceeding. If the limit of 10 retries
is reached and the same response is still being recieved, the function
will continue as it did before with the invalid response text. That will
result in the same exception that was occurring previously, which happens
when the response text is being processed within other parts of the code
that call this function. This error handling may be improved in the …
=> Retry failed REDCap API calls

lib/id3c/api/datastore.py, lib/id3c/api/routes.py, lib/id3c/api/schemas.py, lib/id3c/db/types.py
Adding new API endpoints for single and batch create and update
of sample records, to replace current process of ingestion from
aliquoting sheets.
=> Add accessioning API to add/update sample records

Pipfile.lock, setup.py
Fix failing tests regression introduced by pytest==7.0.0: https://github.com/pytest-dev/pytest/issues/9608#issuecomment-1030355395
Fix fatal exception caused by changes in the way pandas' NATypes are converted to JSON: https://seattle-flu-study.slack.com/archives/CLCKA5AKW/p1644352812859719
=> Pin pandas and pytest to specific versions

lib/id3c/cli/command/etl/__init__.py, lib/id3c/cli/command/etl/fhir.py
New entries are being added to the FHIR bundle for Immunization as part
of the updated UW Retrospectives ETL seattleflu/id3c-customizations#267.
These entries are using standard FHIR format and coding, and are linked to
a FHIR Patient, so in ID3C they will be ingested into the `individual.details`
column rather than `encounter.details`.
The `individual.details` jsonb column has not been utilized yet in ID3C, so this
will be the only data present until other ETLs are updated to include Immunization
entries or other resource entries related to Patients are are added to the FHIR
bundle and this ETL.
=> Update FHIR ETL to include Immunization entries

lib/id3c/cli/command/geocode.py
Occasionally, Smarty Streets will output an error to `stdout` that is not actionable, but since it sends to `stderr` instead of logging, it still shows up in our alerts channel. This change silences the message: `There was an error processing the request. Retrying in <n> seconds.`.
Dave sent [this stackoverflow answer](https://stackoverflow.com/questions/22822267/how-to-capture-print-output-of-another-module) which allows us to capture the output of a module and send it to `stdout`. I modified the answer slightly to capture from `stderr` instead, since this is where Smarty Streets prints this message. I was worried there could be the potential that we would miss some legitamate errors with this method, so I send any printed output from Smarty Streets to logging. If the message starts with …
=> Silence Unwanted Smarty Streets Retry Output

lib/id3c/cli/command/etl/__init__.py
The current ETL processes for creating FHIR bundles include the generation
of random UUIDs which are used as reference identifiers within each bundle.
Since these values are not indicitive of the actual data changing, they
are being removed before comparing the existing and incoming data.
Also being removed is the md5 hashing, which was not necessary for the comparison.
=> Ignore FHIR resource reference IDs when determining if data changed

lib/id3c/cli/command/etl/__init__.py
This change compares incoming values with existing values in the `warehouse.location` table
to decide if there is a need to perform an update. Unnecessary updates add bloat to the
table, which this change will cut down on.
=> Prevent Updates to Unchanged Location Records

lib/id3c/cli/command/etl/fhir.py
Previously, `None` type presence absence results encoded within FHIR bundles were dropped by this pipeline. This change ingests any such results with `presence = null` so that inconclusive results may be ingested as part of the PHSKC ETL.
=> Ingest Inconclusive P/A Results as Null

lib/id3c/cli/command/etl/__init__.py
To prevent gaps in the `individual_id` sequence and unnecessary updates to records
in `warehouse.individual` when there are no changes, the `upsert_individual` function
is being updated to first check if a record exists and then only perform the update
if the relevant columns have different data. Preventing unnecessary updates will help
reduce bloat and provide a more accurate modified date on the record.
=> Rework upsert individual function

lib/id3c/db/__init__.py
This change checks for identifier and metadata changes in sample records prior to upserting
them into the warehouse table. If no changes are detected we can safely skip updates and
thereby make less requests to our table. Note we check identifiers separately because we
often upsert with one or the other.
This change also adds a warning if the function is called and requested to update identifiers
but is only passed 1 identifier. This would be useful if we have a sample with both identifiers
filled out and we are updating it with only one identifier passed in (this would erase the
existing identifier).
=> Prevent Updates to Unchanged Sample Records

lib/id3c/cli/command/manifest.py
Adds an option `--ignore-case` to the manifest diff ID3C command. Running the command without this option retains the current behavior, which is to do a deep diff of manifest files while remaining sensitive to string case. Running the command with this option will perform the same diff, but will treat upper and lowercase strings the same.
=> Add a Case Insensitive Option to Manifest Diff
